version: '2'

services:
  fan-control:
      image: bh.cr/g_aurelien_valade/fan-control_arm32 
      privileged: true
      restart: always
      labels:
         io.balena.features.sysfs: 1
      environment:
          - 'THERMAL_ZONE=0'
          - 'REFRESH_DELAY=10'
          - 'PWM="1,0"'
          - 'PWM_TEMPS="0,40,50,70"'
          - 'PWM_DUTY="0,100,1000,40000"'

